version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing frontend dependencies...
      - echo "Working directory at start:"
      - pwd
      - echo "Directory structure:"
      - ls -la
      - echo "Navigating to packages directory for build:"
      - cd ..
      - pwd
      - echo "Contents of packages directory:"
      - ls -la
      - npm ci --include=dev
      - echo "Checking installed packages:"
      - npm list --depth=0

  pre_build:
    commands:
      - echo Starting frontend build...
      - echo Running code quality checks...
      - npm run lint || echo "Lint check skipped - no linter configured"
      - echo Running unit tests...
      - npm test -- --coverage --watchAll=false || echo "Tests skipped - no tests configured"
      - echo Building frontend with Vite...
      - echo "Current working directory before build:"
      - pwd
      - npm run build
      - echo Verifying build artifacts...
      - echo "Checking for build output..."
      - ls -la web-dist/ 2>/dev/null || echo "web-dist not found, checking web/dist/"
      - ls -la web/dist/ 2>/dev/null || echo "web/dist not found, checking dist/"
      - ls -la dist/ 2>/dev/null || echo "dist not found"
      - echo "Current directory structure after build:"
      - ls -la

  build:
    commands:
      - echo Syncing frontend assets to S3...
      - |
        if [ -d "web-dist" ]; then
          echo "Found web-dist directory, syncing to S3..."
          aws s3 sync ./web-dist s3://$FRONTEND_BUCKET --delete --cache-control "public, max-age=31536000"
        elif [ -d "web/dist" ]; then
          echo "Found web/dist directory, syncing to S3..."
          aws s3 sync ./web/dist s3://$FRONTEND_BUCKET --delete --cache-control "public, max-age=31536000"
        elif [ -d "dist" ]; then
          echo "Found dist directory, syncing to S3..."
          aws s3 sync ./dist s3://$FRONTEND_BUCKET --delete --cache-control "public, max-age=31536000"
        else
          echo "ERROR: No build output directory found!"
          exit 1
        fi
      - echo Creating CloudFront invalidation...
      - INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*" --query 'Invalidation.Id' --output text) || echo "CloudFront invalidation failed - rate limited, but S3 sync was successful"
      - echo "CloudFront invalidation result $INVALIDATION_ID"

  post_build:
    commands:
      - echo "Frontend deployment completed on $(date)"
      - echo Verifying deployment...
      - sleep 30
      - echo "Getting CloudFront domain URL..."
      - CLOUDFRONT_URL=$(aws cloudfront get-distribution --id $CLOUDFRONT_DIST_ID --query 'Distribution.DomainName' --output text)
      - echo "CloudFront URL $CLOUDFRONT_URL"
      - curl -f https://$CLOUDFRONT_URL || echo "Frontend health check failed, but continuing..."

artifacts:
  files:
    - web-dist/**/*
    - web/dist/**/*
    - dist/**/*
    - coverage/**/*
  name: frontend-artifacts

reports:
  jest-reports:
    files:
      - coverage/lcov.info
    file-format: 'CLOVERXML'

cache:
  paths:
    - node_modules/**/*
    - ../node_modules/**/*
    - /root/.npm/**/*