version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing frontend dependencies...
      - cd ops/packages/web
      - npm ci

  pre_build:
    commands:
      - echo Starting frontend build...
      - echo Running code quality checks...
      - npm run lint || echo "Lint check skipped - no linter configured"
      - echo Running unit tests...
      - npm test -- --coverage --watchAll=false || echo "Tests skipped - no tests configured"
      - echo Building frontend with Vite...
      - npm run build
      - echo Verifying build artifacts...
      - ls -la dist/

  build:
    commands:
      - echo Syncing frontend assets to S3...
      - aws s3 sync ./dist s3://$FRONTEND_BUCKET --delete --cache-control "public, max-age=31536000"
      - echo Creating CloudFront invalidation...
      - >
        INVALIDATION_ID=$(aws cloudfront create-invalidation 
        --distribution-id $CLOUDFRONT_DIST_ID 
        --paths "/*" 
        --query 'Invalidation.Id' 
        --output text)
      - echo "CloudFront invalidation created with ID $INVALIDATION_ID"

  post_build:
    commands:
      - echo "Frontend deployment completed on $(date)"
      - echo Verifying deployment...
      - sleep 30
      - curl -f https://$CLOUDFRONT_DOMAIN || echo "Frontend health check failed, but continuing..."

artifacts:
  files:
    - ops/packages/web/dist/**/*
    - ops/packages/web/coverage/**/*
  name: frontend-artifacts

reports:
  jest-reports:
    files:
      - ops/packages/web/coverage/lcov.info
    file-format: 'CLOVERXML'

cache:
  paths:
    - ops/packages/web/node_modules/**/*
    - /root/.npm/**/*