version: 0.2

env:
  variables:
    NODE_ENV: "production"
    DOCKER_BUILDKIT: "1"

phases:
  install:
    runtime-versions:
      nodejs: 18
      docker: 20
    commands:
      - echo Installing backend dependencies...
      - cd ops/packages/api
      - npm ci

  pre_build:
    commands:
      - echo Starting backend API build...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - echo Running code quality checks...
      - npm run lint || echo "Lint check skipped - no linter configured"
      - echo Running unit tests...
      - npm test -- --coverage --watchAll=false || echo "Tests skipped - no tests configured"
      - echo Preparing Docker context...
      - cd ../..
      - echo Current directory structure:
      - ls -la

  build:
    commands:
      - echo Building and pushing Docker image...
      - echo "Build started on $(date)"
      - docker build -f ops/packages/Dockerfile -t $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker build -f ops/packages/Dockerfile -t $ECR_REPO:latest .
      - echo Running security scan on Docker image...
      - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --exit-code 0 --no-progress --format json --output trivy-results.json $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION || true
      - echo Pushing Docker images to ECR...
      - docker push $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_REPO:latest
      - |
        if [ "$DEPLOYMENT_ACTION" = "deploy" ]; then
          echo Updating ECS service with new image...
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
          echo Waiting for service to stabilize...
          aws ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE
        else
          echo Build completed. Waiting for manual approval for deployment...
        fi

  post_build:
    commands:
      - echo "Backend API deployment completed on $(date)"
      - echo Verifying deployment health...
      - sleep 30
      - curl -f $APP_HEALTH_URL/health || echo "Health check failed, but continuing..."
      - echo Getting service endpoint...
      - aws elbv2 describe-load-balancers --names $ALB_NAME --query 'LoadBalancers[0].DNSName' || echo "ALB not found"
      - echo Generating deployment manifest...
      - cd ops/packages
      - printf '[{"name":"api","imageUri":"%s"}]' $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - ops/packages/imagedefinitions.json
    - ops/packages/api/coverage/**/*
    - trivy-results.json
  name: backend-artifacts

reports:
  jest-reports:
    files:
      - ops/packages/api/coverage/lcov.info
    file-format: 'CLOVERXML'
  security-scan:
    files:
      - trivy-results.json
    file-format: 'JSON'

cache:
  paths:
    - ops/packages/api/node_modules/**/*
    - /root/.npm/**/*