version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing frontend dependencies...
      - echo "Working directory at start:"
      - pwd
      - echo "Directory structure:"
      - ls -la
      - echo "Checking if ops directory exists:"
      - ls -la ops/ || echo "ops directory not found"
      - |
        if [ -d "ops/packages" ]; then
          echo "Found ops/packages directory"
          cd ops/packages
        else
          echo "ERROR: ops/packages directory not found!"
          echo "Available directories:"
          find . -name "packages" -type d 2>/dev/null || echo "No packages directory found"
          exit 1
        fi
      - echo "Now in ops/packages:"
      - pwd
      - echo "Contents of ops/packages:"
      - ls -la
      - npm ci --include=dev
      - echo "Checking installed packages:"
      - npm list --depth=0

  pre_build:
    commands:
      - echo Starting frontend build...
      - echo Running code quality checks...
      - npm run lint || echo "Lint check skipped - no linter configured"
      - echo Running unit tests...
      - npm test -- --coverage --watchAll=false || echo "Tests skipped - no tests configured"
      - echo Building frontend with Vite...
      - echo "Current working directory before build:"
      - pwd
      - npm run build
      - echo Verifying build artifacts...
      - echo "Checking for build output..."
      - ls -la web-dist/ 2>/dev/null || echo "web-dist not found, checking web/dist/"
      - ls -la web/dist/ 2>/dev/null || echo "web/dist not found, checking current directory"
      - echo "Current directory structure after build:"
      - ls -la

  build:
    commands:
      - echo Syncing frontend assets to S3...
      - |
        if [ -d "web-dist" ]; then
          echo "Found web-dist directory, syncing to S3..."
          aws s3 sync ./web-dist s3://$FRONTEND_BUCKET --delete --cache-control "public, max-age=31536000"
        elif [ -d "web/dist" ]; then
          echo "Found web/dist directory, syncing to S3..."
          aws s3 sync ./web/dist s3://$FRONTEND_BUCKET --delete --cache-control "public, max-age=31536000"
        else
          echo "ERROR: No build output directory found!"
          exit 1
        fi
      - echo Creating CloudFront invalidation...
      - >
        INVALIDATION_ID=$(aws cloudfront create-invalidation 
        --distribution-id $CLOUDFRONT_DIST_ID 
        --paths "/*" 
        --query 'Invalidation.Id' 
        --output text)
      - echo "CloudFront invalidation created with ID $INVALIDATION_ID"

  post_build:
    commands:
      - echo "Frontend deployment completed on $(date)"
      - echo Verifying deployment...
      - sleep 30
      - echo "Getting CloudFront domain URL..."
      - CLOUDFRONT_URL=$(aws cloudfront get-distribution --id $CLOUDFRONT_DIST_ID --query 'Distribution.DomainName' --output text)
      - echo "CloudFront URL: $CLOUDFRONT_URL"
      - curl -f https://$CLOUDFRONT_URL || echo "Frontend health check failed, but continuing..."

artifacts:
  files:
    - ops/packages/web-dist/**/*
    - ops/packages/web/dist/**/*
    - ops/packages/coverage/**/*
  name: frontend-artifacts

reports:
  jest-reports:
    files:
      - ops/packages/coverage/lcov.info
    file-format: 'CLOVERXML'

cache:
  paths:
    - ops/packages/web/node_modules/**/*
    - /root/.npm/**/*